### ISSUE TITLE
version.php not found

### ISSUE THREAD

**Issue by fulcus** [C0D3D3V/Moodle-Downloader-2#105]
I have logged in using sso with `moodle-dl --init --sso` and everything worked as expected. Then if I launch `moodle-dl` it throws this error:
```
The following error occurred during execution:
The Moodle System rejected the Request. Details: moodle_exception (Errorcode: missingversionfile, Message: Coding error: version.php file is missing for the component mod_tutorialbooking)
``` 

## `MoodleDownloader.log` 

```
2021-09-14 10:39:39  INFO  {main}  --- moodle-dl started ---------------------
2021-09-14 10:39:39  ERROR  {main}  Error while trying to load the Configuration! No config found! Exiting...
2021-09-14 11:01:24  INFO  {main}  --- moodle-dl started ---------------------
2021-09-14 11:01:25  ERROR  {main}  Traceback (most recent call last):
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/main.py", line 246, in run_main
    changed_courses = moodle.fetch_state()
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/moodle_service.py", line 233, in fetch_state
    userid, version = first_contact_handler.fetch_userid_and_version()
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/first_contact_handler.py", line 20, in fetch_userid_and_version
    result = self.request_helper.post_REST('core_webservice_get_site_info')
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/request_helper.py", line 135, in post_REST
    json_result = self._initial_parse(response)
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/request_helper.py", line 281, in _initial_parse
    raise RequestRejectedError(
moodle_dl.moodle_connector.request_helper.RequestRejectedError: The Moodle System rejected the Request. Details: moodle_exception (Errorcode: missingversionfile, Message: Coding error: version.php file is missing for the component mod_tutorialbooking)

2021-09-14 11:04:08  INFO  {main}  --- moodle-dl started ---------------------
2021-09-14 11:04:09  ERROR  {main}  Traceback (most recent call last):
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/main.py", line 246, in run_main
    changed_courses = moodle.fetch_state()
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/moodle_service.py", line 233, in fetch_state
    userid, version = first_contact_handler.fetch_userid_and_version()
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/first_contact_handler.py", line 20, in fetch_userid_and_version
    result = self.request_helper.post_REST('core_webservice_get_site_info')
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/request_helper.py", line 135, in post_REST
    json_result = self._initial_parse(response)
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/request_helper.py", line 281, in _initial_parse
    raise RequestRejectedError(
moodle_dl.moodle_connector.request_helper.RequestRejectedError: The Moodle System rejected the Request. Details: moodle_exception (Errorcode: missingversionfile, Message: Coding error: version.php file is missing for the component mod_tutorialbooking)

2021-09-14 11:04:49  INFO  {main}  --- moodle-dl started ---------------------
2021-09-14 11:04:49  DEBUG  {main}  moodle-dl version: 2.1.2.6
2021-09-14 11:04:49  DEBUG  {main}  python version: 3.8.10
2021-09-14 11:04:49  DEBUG  {main}  Is ffmpeg available: True
2021-09-14 11:04:49  DEBUG  {main}  Loading config...
2021-09-14 11:04:49  DEBUG  {state_recorder}  Database Version: 4
2021-09-14 11:04:49  DEBUG  {main}  Checking for changes for the configured Moodle-Account....
2021-09-14 11:04:49  DEBUG  {moodle_service}  Fetching current Moodle State...
2021-09-14 11:04:49  ERROR  {main}  Traceback (most recent call last):
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/main.py", line 246, in run_main
    changed_courses = moodle.fetch_state()
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/moodle_service.py", line 233, in fetch_state
    userid, version = first_contact_handler.fetch_userid_and_version()
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/first_contact_handler.py", line 20, in fetch_userid_and_version
    result = self.request_helper.post_REST('core_webservice_get_site_info')
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/request_helper.py", line 135, in post_REST
    json_result = self._initial_parse(response)
  File "/home/fulco/.local/lib/python3.8/site-packages/moodle_dl/moodle_connector/request_helper.py", line 281, in _initial_parse
    raise RequestRejectedError(
moodle_dl.moodle_connector.request_helper.RequestRejectedError: The Moodle System rejected the Request. Details: moodle_exception (Errorcode: missingversionfile, Message: Coding error: version.php file is missing for the component mod_tutorialbooking)

2021-09-14 11:04:49  DEBUG  {mail_service}  Mail-Notifications not configured, skipping.
2021-09-14 11:04:49  DEBUG  {telegram_service}  Telegram-Notifications not configured, skipping.
2021-09-14 11:04:49  DEBUG  {xmpp_service}  XMPP-Notifications not configured, skipping.
2021-09-14 11:04:49  DEBUG  {main}  Exception-Handling completed. Exiting...
```

## Technical details
Ubuntu 20.04

**Comment by C0D3D3V** [comment]
looks like a issue with your moodle instance. Does the moodle app work with your instance? Can you send me the url of the instance? In theory we could skip the `core_webservice_get_site_info` call, so I can handle the error and skip the retrival of the userid (but then you have to set the userid in the config manual).

**Comment by fulcus** [comment]
https://webeep.polimi.it/ 

Yes that would be awesome!!

**Comment by C0D3D3V** [comment]
I created an account at your university, but unfortunately I still can't log in at moodle. Therefore I can not test it myself. But I will try to implement this in the next days and test it on my own moodle. I will let you know when it is ready.

**Comment by fulcus** [comment]
Thanks a lot! If you need any help with testing or anything else hmu on telegram @fulcus

**Comment by fulcus** [comment]
Hi, do you have any update on this issue? A bunch of people from my uni contacted me about it. If you need a hand just lmk.

**Comment by C0D3D3V** [comment]
I am very sorry that I could not work on it in the last days. I was on vacation (In Austria much hiking <3). And am just in the middle of moving. On Wednesday I will tackle it :)

**Comment by C0D3D3V** [comment]
Eh, I tackled the issue this morning. I haven't managed to log in to your Moodle in the Moodle App yet. But I found out that your Moodle is enabled to view the tokens in the settings under "Security Keys" (https://webeep.polimi.it/user/managetoken.php?sesskey=...).   I set the token in the settings of my Moodle downloader (`"token": "7a90a25bdfxxxxx57899669d39",`). And I have had no problems downloading the courses I am enrolled in. 


I therefore assume that the bug in your Moodle has been corrected, and `core_webservice_get_site_info` no longer throws errors. 
Please check if it works for you now. 
I will still try to implement a manual workaround.

**Comment by C0D3D3V** [comment]
You can now set the version number and the user id manually. I have also already done a writeup: https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Set-user-id-and-Moodle-version-number-manually

It will be included in the next release, but you can also test it by downloading the branch manually.

**Comment by fulcus** [comment]
I confirm that it works. Thanks a lot!!
