### ISSUE TITLE
dml_missing_record_exception in Version 4.0.2

### ISSUE THREAD

**Issue by niclasboy** [C0D3D3V/Moodle-Downloader-2#162]
## Describe the bug

Hello,
after my university updated there Moodle to Version 4.0.2 the Moodle-Downloader-2 doesnt work anymore. Does somebody of you know a workaround? 

Best Regard
Niclas
 

``` Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/moodle_dl/main.py", line 268, in run_main
    changed_courses = moodle.fetch_state()
  File "/usr/local/lib/python3.7/dist-packages/moodle_dl/moodle_connector/moodle_service.py", line 338, in fetch_state
    forums = forums_handler.fetch_forums_posts(forums, last_timestamps_per_forum)
  File "/usr/local/lib/python3.7/dist-packages/moodle_dl/moodle_connector/forums_handler.py", line 163, in fetch_forums_posts
    forums_files = self._get_files_of_discussions(latest_discussions)
  File "/usr/local/lib/python3.7/dist-packages/moodle_dl/moodle_connector/forums_handler.py", line 195, in _get_files_of_discussions
    posts_result = self.request_helper.post_REST('mod_forum_get_forum_discussion_posts', data)
  File "/usr/local/lib/python3.7/dist-packages/moodle_dl/moodle_connector/request_helper.py", line 166, in post_REST
    json_result = self._initial_parse(response)
  File "/usr/local/lib/python3.7/dist-packages/moodle_dl/moodle_connector/request_helper.py", line 311, in _initial_parse
    + f' Details: {exception} (Errorcode: {errorcode}, Message: {message})'
moodle_dl.moodle_connector.request_helper.RequestRejectedError: The Moodle System rejected the Request. Details: dml_missing_record_exception (Errorcode: invalidrecord, Message: Der Datensatz kann nicht in der Datenbanktabelle external_functions gefunden werden.)

The following error occurred during execution:
The Moodle System rejected the Request. Details: dml_missing_record_exception (Errorcode: invalidrecord, Message: Der Datensatz kann nicht in der Datenbanktabelle external_functions gefunden werden.) 
```

 - OS: Debian 10
 - Version: moodle-dl-2.2.2.1
 -  Moodle Version (I think): 4.0.2

**Comment by niclasboy** [comment]
Thank you, yeah, this will work. 
I thought I have tried that. ;)

**Comment by C0D3D3V** [comment]
This should be fixed in version 2.2.2.3. Please test it.

**Comment by C0D3D3V** [comment]
Btw. I already wrote about this issue in this wiki [post]( https://github.com/C0D3D3V/Moodle-Downloader-2/wiki/Moodle-API---Forums) 2 years ago :D

**Comment by niclasboy** [comment]
Hey, excuse my late reply, it works. Thank you!
