### ISSUE TITLE
Some description files make the download process halt indefinitely

### ISSUE THREAD

**Issue by stefa168** [C0D3D3V/Moodle-Downloader-2#30]
After fixing the UTF-8 encoding issue, I tried re-starting the download process.
After some time downloading part of the files, it halts after throwing this error:

```
Moodle Downloader starting...
Loading config...
Checking for changes for the configured Moodle-Account...
Download course information   1/  1 [Linguaggi e Par..|  1771]
Start downloading changed files...
Total:  31%        17375/       54549kb T0:  97% T1:   0% T2:   0% T3:   0% T4:Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\myuser\PycharmProjects\Moodle-Downloader-2\download_service\url_target.py", line 205, in download
    self.create_description()
  File "C:\Users\myuser\PycharmProjects\Moodle-Downloader-2\download_service\url_target.py", line 167, in create_description
    self.file.saved_to = self._rename_if_exists(self.file.saved_to)
  File "C:\Users\myuser\PycharmProjects\Moodle-Downloader-2\download_service\url_target.py", line 121, in _rename_if_exists
    Path(new_path).touch()
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\lib\pathlib.py", line 1220, in touch
    fd = self._raw_open(flags, mode)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\lib\pathlib.py", line 1028, in _raw_open
    return self._accessor.open(self, flags, mode)
OSError: [Errno 22] Invalid argument: "Linguaggi e Paradigmi di Programmazione 2019\\7 ottobre - 13 ottobre\\Teoria\r\nFare riferimento all'articolo di Hudak (19.md"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\myuser\PycharmProjects\Moodle-Downloader-2\download_service\downloader.py", line 41, in run
    response = url_target.download(self.thread_id)
  File "C:\Users\myuser\PycharmProjects\Moodle-Downloader-2\download_service\url_target.py", line 231, in download
    os.path.getsize(self.file.saved_to) == 0):
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python37-32\lib\genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
OSError: [WinError 123] La sintassi del nome del file, della directory o del volume non è corretta: "Linguaggi e Paradigmi di Programmazione 2019\\7 ottobre - 13 ottobre\\Teoria\r\nFare riferimento all'articolo di Hudak (19.md"

Total:  32%        17670/       54549kb T0:   0% T1:   0% T2:   0% T3:   0% T4:
Process finished with exit code -1 <---- Here I manually stopped the program

```

[This is the HTML](https://github.com/C0D3D3V/Moodle-Downloader-2/files/4601834/problematic.HTML.txt) of the description section that causes the problem. 

I believe it is caused by newlines in the path ("Teoria\r\nFare riferimento all'articolo di Hudak (19.md")

**Comment by C0D3D3V** [comment]
I see. Yes new lines are not explicitly forbidden in Windows Path but can cause problems.  I will make a fix today.

**Comment by C0D3D3V** [comment]
Could you test if  c57fbff helped?

**Comment by stefa168** [comment]
Yes, now it downloaded everything!
It also managed to reach 102% of completion

Thanks for your time!

**Comment by C0D3D3V** [comment]
ok great :) Yes it is posible to reach more then 100% because moodle does not store the file size for every file, so the predicted total size is lower then the real size.
