### ISSUE TITLE
youtube-dl downloading error

### ISSUE THREAD

**Issue by Azuxul** [C0D3D3V/Moodle-Downloader-2#70]
## Avoid duplicates
* [x] Bug is not already reported in another issue

## Describe the bug

When trying to download moodle content, an error appear with youtube-dl.
The issue append with this web site : https://peerlearningexperience.3ds.com/my/

 

## Steps to reproduce the issue

Run moodle-dl with download_linked_files and download_links_in_descriptions set to true. No issue when set to false.

<details>
  <summary>config.json</summary>
 
  ```JSON
  {
    "token": "xxx",
    "moodle_domain": "xxx",
    "moodle_path": "/moodle/",
    "download_submissions": true,
    "download_descriptions": true,
    "download_databases": true,
    "download_linked_files": true,
    "download_links_in_descriptions": true,
    "download_domains_blacklist": [
        "youtube.com",
        "wooclap.com"
    ],
    "download_forums": true,
    "download_also_with_cookie": true
}
  ```
  
</details>

![image](https://user-images.githubusercontent.com/11092555/103157497-8cb01480-47b3-11eb-9525-22afac1e89a6.png)

 

<details>
  <summary>MoodleDownloader.log</summary>
 
  ```
  2020-12-26 19:45:22  INFO  {main}  --- moodle-dl started ---------------------
2020-12-26 19:45:22  DEBUG  {main}  moodle-dl version: 2.1.1.2
2020-12-26 19:45:22  DEBUG  {main}  python version: 3.6.6
2020-12-26 19:45:22  DEBUG  {main}  Is ffmpeg available: True
2020-12-26 19:45:22  DEBUG  {main}  Loading config...
2020-12-26 19:45:22  DEBUG  {state_recorder}  Database Version: 4
2020-12-26 19:45:22  DEBUG  {main}  Checking for changes for the configured Moodle-Account....
2020-12-26 19:45:22  DEBUG  {moodle_service}  Fetching current Moodle State...
2020-12-26 19:45:23  DEBUG  {results_handler}  Detected moodle version: 2020061501
2020-12-26 19:45:35  DEBUG  {moodle_service}  Checking for changes...
2020-12-26 19:45:36  DEBUG  {main}  Start downloading changed files...
2020-12-26 19:45:36  DEBUG  {download_service}  Queue contains 1 URLTargets
2020-12-26 19:45:36  DEBUG  {downloader}  T0 - Downloader thread was started
2020-12-26 19:45:36  DEBUG  {url_target}  T0 - Starting downloading of: URLTarget (File (module_id: 94181, section_name: "Tutoriels externes", module_name: "Peer Learning Experience", content_filepath: /, content_filename: "Peer Learning Experience", content_fileurl: "https://peerlearningexperience.3ds.com/my/", content_filesize: 0, content_timemodified: 1603127303, module_modname: url, content_type: url, content_isexternalfile: False, saved_to: "", time_stamp: 0, modified: False, moved: False, deleted: False, notified: False, hash: None, file_id: None, old_file_id: None), Course (id: 1878, fullname: "AN_3Dexp Ressources", overwrite_name_with: "None", create_directory_structure: True, files: 1), False, Error: None)
2020-12-26 19:45:36  DEBUG  {downloader}  T1 - Downloader thread was started
2020-12-26 19:45:36  DEBUG  {url_target}  T0 - Seting up target file: "\\?\C:\Users\Lancelot\Documents\Cours\AM A1\Moodle\AN_3Dexp Ressources\Tutoriels externes\Peer Learning Experience.URL"
2020-12-26 19:45:36  DEBUG  {downloader}  T1 - Downloader thread is finished
2020-12-26 19:45:36  DEBUG  {downloader}  T2 - Downloader thread was started
2020-12-26 19:45:36  DEBUG  {downloader}  T3 - Downloader thread was started
2020-12-26 19:45:36  DEBUG  {downloader}  T4 - Downloader thread was started
2020-12-26 19:45:36  DEBUG  {downloader}  T2 - Downloader thread is finished
2020-12-26 19:45:36  DEBUG  {url_target}  T0 - Creating a shortcut
2020-12-26 19:45:36  DEBUG  {downloader}  T3 - Downloader thread is finished
2020-12-26 19:45:36  DEBUG  {downloader}  T4 - Downloader thread is finished
2020-12-26 19:45:36  DEBUG  {url_target}  T0 - Try to download linked file https://peerlearningexperience.3ds.com/my/
2020-12-26 19:45:36  DEBUG  {url_target}  T0 - URL was 6 time(s) redirected
2020-12-26 19:45:37  DEBUG  {url_target}  T0 - youtube-dl Debug: [generic] plexp: Requesting header
2020-12-26 19:45:38  DEBUG  {url_target}  T0 - youtube-dl Warning: Falling back on generic information extractor.
2020-12-26 19:45:38  DEBUG  {url_target}  T0 - youtube-dl Debug: [generic] plexp: Downloading webpage
2020-12-26 19:45:38  DEBUG  {url_target}  T0 - youtube-dl Debug: [generic] plexp: Extracting information
2020-12-26 19:45:38  DEBUG  {url_target}  T0 - youtube-dl Debug: [download] Downloading playlist: Discover the Peer Learning Experience™  | 3DEXPERIENCE Edu
2020-12-26 19:45:38  DEBUG  {url_target}  T0 - youtube-dl Debug: [generic] playlist Discover the Peer Learning Experience™  | 3DEXPERIENCE Edu: Collected 1 video ids (downloading 1 of them)
2020-12-26 19:45:38  DEBUG  {url_target}  T0 - youtube-dl Debug: [download] Downloading video 1 of 1
2020-12-26 19:45:38  DEBUG  {url_target}  T0 - youtube-dl Debug: [youtube] 1OAE3dOegeg: Downloading webpage
2020-12-26 19:45:38  ERROR  {url_target}  T0 - youtube-dl Error: ERROR: 1OAE3dOegeg: YouTube said: Unable to extract video data
2020-12-26 19:45:38  DEBUG  {url_target}  T0 - youtube-dl Debug: [download] Finished downloading playlist: Discover the Peer Learning Experience™  | 3DEXPERIENCE Edu
2020-12-26 19:45:38  ERROR  {url_target}  T0 - Error while trying to download file: URLTarget (File (module_id: 94181, section_name: "Tutoriels externes", module_name: "Peer Learning Experience", content_filepath: /, content_filename: "Peer Learning Experience", content_fileurl: "https://peerlearningexperience.3ds.com/my/", content_filesize: 0, content_timemodified: 1603127303, module_modname: url, content_type: url, content_isexternalfile: False, saved_to: "\\?\C:\Users\Lancelot\Documents\Cours\AM A1\Moodle\AN_3Dexp Ressources\Tutoriels externes\Peer Learning Experience.URL", time_stamp: 1609008336, modified: False, moved: False, deleted: False, notified: False, hash: None, file_id: None, old_file_id: None), Course (id: 1878, fullname: "AN_3Dexp Ressources", overwrite_name_with: "None", create_directory_structure: True, files: 1), False, Error: Traceback (most recent call last):
  File "C:\Users\Lancelot\Documents\Cours\AM A1\Moodle\Moodle-Downloader-2-2.1.1.2\moodle_dl\download_service\url_target.py", line 727, in download
    self.try_download_link(add_token, False, False)
  File "C:\Users\Lancelot\Documents\Cours\AM A1\Moodle\Moodle-Downloader-2-2.1.1.2\moodle_dl\download_service\url_target.py", line 484, in try_download_link
    'Youtube-dl could not download the URL. For details see youtube-dl error messages in the log file'
RuntimeError: Youtube-dl could not download the URL. For details see youtube-dl error messages in the log file

Error:Youtube-dl could not download the URL. For details see youtube-dl error messages in the log file)
2020-12-26 19:45:38  DEBUG  {downloader}  T0 - URLTarget reports failure!
2020-12-26 19:45:38  DEBUG  {downloader}  T0 - Downloader thread is finished
2020-12-26 19:45:39  INFO  {main}  No changes found for the configured Moodle-Account.
2020-12-26 19:45:39  DEBUG  {main}  All done. Exiting...

  ```
  
</details>

## Technical details

- OS: Windows 10 1909
- Version 2.1.1.2

## Expected behavior

No errors ...

## Possible Fix

Maybe a youtube-dl issue and not a moodle-dl issue ??

**Comment by C0D3D3V** [comment]
Sorry for the late response and merry christmas :)

You are right. In "AN_3Dexp Ressources\Tutoriels externes" was the link to "Peer Learning Experience" (https://peerlearningexperience.3ds.com/my/) found and as with every external link moodle-dl tries to download this link first with youtube-dl.  Youtube-dl found a video on the webpage (as you can also see the video if you open the link), youtube-dl is then marked as essential (so the download of the link is only sucessfull if youtube-dl finishes sucessful), because we want to download a video if there is one. But then youtube-dl faild with the Error "Unable to extract video data", thats why the download is marked as faild (and the URL-file that was created is removed for cleanup reasons).

So the error "Unable to extract video data" of youtube-dl could have multiple reasons, maybe it was temporary unavailible or your youtube-dl temporary blocked.

But as I look at the website, it does not seem essential to download the title video, maybe you want just ignore the error. 
Currently there is no super easy way to skip one single download. I plan to add some more functions to improve the situation. 

In the meantime you could do one of the following options:
- set download_linked_files for one run to false
- add the ...3ds.com domain to the download_domains_blacklist and run moodle-dl once
- run moodle-dl for once with the option --skip-downloading-files


I will leave the issue open, and post here an update when there is an easier way to skip a download.

**Comment by Azuxul** [comment]
Thanks for your response and merry christmas too !

After running moodle-dl with `download_linked_files` set to `false` there is no more issue.

**Comment by C0D3D3V** [comment]
This is related to #63

**Comment by C0D3D3V** [comment]
It is now possible to ignore youtube-dl errors. See #63
