### ISSUE TITLE
NewConnectionError not managed

### ISSUE THREAD

**Issue by marcoscale98** [C0D3D3V/Moodle-Downloader-2#73]
## Avoid duplicates
* [ ] Bug is not already reported in another issue
 
## Steps to reproduce the issue
Start downloading the courses and then turn off internet. A series of exceptions raised.

## Log
```
2020-12-09 08:54:04  ERROR  {url_target}  T0 - Error while trying to download file: URLTarget (File (module_id: 129335, section_name: "Parte 3 (docente L. Di Caro)", module_name: "Soluzione content-to-form", content_filepath: /, content_filename: "Soluzione content-to-form", content_fileurl: "https://informatica.i-learn.unito.it/webservice/pluginfile.php/216487/mod_page/content/index.html?forcedownload=1", content_filesize: 0, content_timemodified: 1588595059, module_modname: index_mod-page, content_type: file, content_isexternalfile: False, saved_to: "\\?\H:\moodle\TECNOLOGIE DEL LINGUAGGIO NATURALE (INF0094)\Parte 3 (docente L. Di Caro)\Soluzione content-to-form", time_stamp: 0, modified: False, moved: False, deleted: False, notified: False, hash: None, file_id: None, old_file_id: None), Course (id: 1939, fullname: "TECNOLOGIE DEL LINGUAGGIO NATURALE (INF0094)", overwrite_name_with: "None", create_directory_structure: True, files: 365), False, Error: Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "c:\program files\python37\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "c:\program files\python37\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "c:\program files\python37\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "c:\program files\python37\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "c:\program files\python37\lib\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "c:\program files\python37\lib\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001B6B947B748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\program files\python37\lib\site-packages\urllib3\connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "c:\program files\python37\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='informatica.i-learn.unito.it', port=443): Max retries exceeded with url: /webservice/pluginfile.php/216487/mod_page/content/index.html?forcedownload=1&token=610187dd8c873f88f584638fcba30d72 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B6B947B748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marco\AppData\Roaming\Python\Python37\site-packages\moodle_dl\download_service\url_target.py", line 713, in download
    self.try_download_link(add_token, True, False)
  File "C:\Users\marco\AppData\Roaming\Python\Python37\site-packages\moodle_dl\download_service\url_target.py", line 383, in try_download_link
    allow_redirects=True,
  File "c:\program files\python37\lib\site-packages\requests\sessions.py", line 565, in head
    return self.request('HEAD', url, **kwargs)
  File "c:\program files\python37\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\program files\python37\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\program files\python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='informatica.i-learn.unito.it', port=443): Max retries exceeded with url: /webservice/pluginfile.php/216487/mod_page/content/index.html?forcedownload=1&token=610187dd8c873f88f584638fcba30d72 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B6B947B748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

Error:HTTPSConnectionPool(host='informatica.i-learn.unito.it', port=443): Max retries exceeded with url: /webservice/pluginfile.php/216487/mod_page/content/index.html?forcedownload=1&token=610187dd8c873f88f584638fcba30d72 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001B6B947B748>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')))
```

## Technical details
OS: Windows 10

## Expected behavior
Hide the exceptions and explain to the user what it's happened.

**Comment by C0D3D3V** [comment]
It is not so easy to handle urllib3 errors properly. But I will see what I can do with it. But you are right as it is now it is not nice.

**Comment by C0D3D3V** [comment]
What do you think about this error message:

```
moodle-dl                                                                                                                  SIGEXIT(127) ↵  daniel@DerGeraet   96% ▇ 
Moodle Downloader starting...
Loading config...
Checking for changes for the configured Moodle-Account....
Downloading account information

The following error occurred during execution:
Connection error: HTTPSConnectionPool(host='school.moodledemo.net', port=443): Max retries exceeded with url: /webservice/rest/server.php?moodlewsrestformat=json&wsfunction=core_webservice_get_site_info (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f71504dedc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

**Comment by C0D3D3V** [comment]
If you have more ideas about the topic, you are welcome to open a new issue.

Thanks for the idea, hope the result pleases you.
