### ISSUE TITLE
m3u8 Video Downloads from MEDIAL Video Streaming Activitiy plugin

### ISSUE THREAD

**Issue by CryptoMathician** [C0D3D3V/Moodle-Downloader-2#86]
Hi,

it would be great if it would be possible to download m3u8 Videos from Moodle.
I did it before manually with ffmpeg and I think that shouldn't be a problem to implement it in this moodle downloader. 
The Moodle plugin shall be MEDIAL Video Streaming Activity (https://moodle.org/plugins/mod_helixmedia). 
It would be nice to support th download of Videolectures which is embedded with this plugin.

Thanks in advance!

BR

**Comment by C0D3D3V** [comment]
I have implemented the extractor for your extension. The prerequisite for it to work is that you have set a private token in the configuration, since the extension does not have a mobile view (which I could test). Took me quite a bit of time, hope it helps someone :).

The platform actually provides Dash and HLS videos with a slightly higher quality than the direct download via mp4. I extracted all formats in the extractor. The problem is that for some reason youtube-dl has problems with the certificate from na1stream.medialibrary.com. So if you want all formats (or want to download the format with the best quality) then you have to pass the paramter `--skip-cert-verify` to moodle-dl to ignore the certificate, otherwise it just takes the default download which is actually in good enough quality.

**Comment by CryptoMathician** [comment]
@C0D3D3V thank you for the implementation! Unfortunately, I get an error. This is the error:

```
2021-10-08 04:57:56  ERROR  {url_target}  T3 - youtube-dl Error: ERROR: Unable to launch helixmedia video
2021-10-08 04:57:56  ERROR  {url_target}  T3 - Error while trying to download file: URLTarget (File (module_id: <id>, section_name: "<section_name>", module_name: "<video_name>", content_filepath: /, content_filename: "<video_name>", content_fileurl: "https://<moodle_domain>/mod/helixmedia/view.php?id=1379333", content_filesize: 0, content_timemodified: 0, module_modname: cookie_mod-helixmedia, content_type: cookie_mod, content_isexternalfile: True, saved_to: "<module_name>/<section>/<video_name>", time_stamp: 0, modified: False, moved: False, deleted: False, notified: False, hash: None, file_id: None, old_file_id: None), Course (id: 27587, fullname: "<module_name>", overwrite_name_with: "None", create_directory_structure: True, files: 29), False, Error: Youtube-dl could not download the URL. For details see youtube-dl error messages in the log file. You can ignore this error by running `moodle-dl --ignore-ytdl-errors` once.)
2021-10-08 04:57:56  ERROR  {url_target}  T3 - Traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/moodle_dl/download_service/url_target.py", line 761, in download
    self.try_download_link(add_token, True, True)
  File "/usr/lib/python3.9/site-packages/moodle_dl/download_service/url_target.py", line 502, in try_download_link
    raise RuntimeError(
RuntimeError: Youtube-dl could not download the URL. For details see youtube-dl error messages in the log file. You can ignore this error by running `moodle-dl --ignore-ytdl-errors` once.
```
As you mentioned I used a private token and I also used `--skip-cert-verify`.
When I use `--ignore-ytdl-errors` I get php files instead of the videos.

Maybe it makes sense that these videos are streamed with the m3u8 format? 
I think the video is embedded into a website and you try to download the website or similar.
It finds the correct website e.g. `https://moodle.uni_domain/mod/helixmedia/view.php?id=1283702`, but this is the website where the video is embedded and it will be loaded via JavaScript or similar and the media link of the video is e.g. `https://streamup.<university_domain>/flash/smil:<some_id>_2.smil/playlist.m3u8?token=(<token>)`.

I downloaded the video via a link (e.g. `https://streamup.<university_domain>/flash/smil:dgC76c1D_2.smil/playlist.m3u8?token=(<token>)`) with ffmpeg via the CLI. To get this link I have to open the devtools in firefox/chrome/chromium and check the traffic for media. Maybe that helps.

**Comment by CryptoMathician** [comment]
I tested the link `https://streamup.<university_domain>/flash/smil:<some_id>_2.smil/playlist.m3u8?token=(<token>)` with `youtube-dl --no-check-certificate https://streamup.<university_domain>/flash/smil:<some_id>_2.smil/playlist.m3u8?token=(<token>)` and it works. Is there a way to build up the correct link of the video via the website `https://moodle.uni_domain/mod/helixmedia/view.php?id=1283702` ? 

I tried it with selenium and parsed the website to build this path. As an example I parsed the website with beatifulsoup4 and searched after specific tags e.g. with xpath and parse the <some_id> and the <token> out and build the path to the actual video. 
Is there a way to do something similar or isn't it possible as of the structure of the project?  - I didn't found the time to dive deeply into this project to understand this structure, sorry.

**Comment by C0D3D3V** [comment]
You probably don't need `--skip-cert-verify` because your university has its own server where the certificates are hopefully correct.
