### ISSUE TITLE
Unable to download videos from helio media server.

### ISSUE THREAD

**Issue by jnnkB** [C0D3D3V/Moodle-Downloader-2#92]
## Avoid duplicates
* [x] Bug is not already reported in another issue

## Describe the bug

 
Thanks a lot for providing this cool tool. I'm currently trying to download the videos linked in some of my moodle courses. Many of them are on an own server provided by my university. Some prof said is it a helios server. But it didn't work so far due to some of the authentication stuff my university uses.

I wrote a small script that adds the relevent cookies to my Cookies.txt file. When running the download using

```sh
youtube-dl <file url> --cookies <cookie file>  --verbose --print-traffic
```

I get this error (I removed some information):

<details>
<summary>Error Log</summary>
<pre>
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['<file url>', '--cookies', '<cookies file>', '--verbose', '--print-traffic']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8, pref UTF-8
[debug] youtube-dl version 2021.04.07
[debug] Python version 3.8.6 (CPython)
[debug] exe versions: ffmpeg 4.3.2, ffprobe 4.3.2, rtmpdump 2.4
[debug] Proxy map: {}
[generic] AFE7: Requesting header
send: b'HEAD <path> HTTP/1.1\r\nHost: <host>\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3528.0 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 302 Found\r\n'
header: Date: Tue, 13 Apr 2021 21:50:01 GMT
header: Server: Apache
header: Strict-Transport-Security: max-age=15552000; includeSubdomains; preload
header: Location: <sso url>
header: Connection: close
header: Content-Type: text/html; charset=iso-8859-1
send: b'GET /login?service=https%3a%2f%2fmoodleload.hrz.tu-darmstadt.de%2fFB04_Logik%2fAFE20%2fAFE7.mp4 HTTP/1.1\r\nHost: sso.tu-darmstadt.de\r\nCookie: TGC=eyJhbGciOiJIUzUxMiJ9.WlhsS05tRllRV2xQYVVwRlVsVlphVXhEU21oaVIyTnBUMmxLYTJGWVNXbE1RMHBzWW0xTmFVOXBTa0pOVkVrMFVUQktSRXhWYUZSTmFsVXlTVzR3TGk0M2FFeDJaRU5PVTBKb2IzcGZlalF4UjNSb1FUbEJMak5RT1RGclpXTXpkRnBpVVVVd2VtbHhhV1F5WVdKU2JEWTBURE42TTFwbWJWSlBNSEUyVVZaU1lWbEtVa0ZsTmpNeFFWSmhaVGhQUVdWalUyOTJVMlp1ZUZob2VuSk5TVmRxWVc1Nk1IVkliaTAzYzBSRU5EVmpWakkxTW1weU1rMU9Va3AxUVRJeGVrUjRNV0U0TkdveVFtWTVWR3hzYnpNeFYwdDJRVVpyUlZZMFZtWkhlakpGV2s1Qk1FRjBjMGRDVVRJeFVrZDBhbUY2UkZwWWVHSTBXakZyV2kxS1ZUUlVTRlJSZGxrNWMwOU1NVVJxVWs1MWFsazVlRzlmWkRsUVNHaHpVM2xKWkhvNE1FOXFYMEk0WVRWM1YwcFVTVEkzWVROc1JFVkxPVEEwTFdveFpsQm1aa0kxWkRseFJVbEdXbUZQZFhGVFMzaGphbDgxUVZCak1qVjRNWGxqWm1GTmVVOVFObEpoVUVwd1dGZEJMbnBXZDBGRWRURnJSR294TFZFNFMxQTBlalV3VVhjPQ.9ynKKUqtVPq_g4kMhGesdEl58Jpjn9AqPyB0QFh2jPybJFi6xS-Z3Gq2KykZItz3RGGlAaKdP7Y5dbGUAUQHuA\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3528.0 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 200\r\n'
header: Date: Tue, 13 Apr 2021 21:50:01 GMT
header: Server: Apache
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: 0
header: Strict-Transport-Security: max-age=15768000 ; includeSubDomains
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: DENY
header: X-XSS-Protection: 1; mode=block
header: Content-Type: text/html;charset=UTF-8
header: Content-Language: en
header: Connection: close
header: Transfer-Encoding: chunked
[redirect] Following redirect to https://sso.tu-darmstadt.de/login?service=https%3a%2f%2fmoodleload.hrz.tu-darmstadt.de%2fFB04_Logik%2fAFE20%2fAFE7.mp4
[generic] login?service=https://moodleload.hrz.tu-darmstadt.de/FB04_Logik/AFE20/AFE7: Requesting header
send: b'HEAD /login?service=https%3a%2f%2fmoodleload.hrz.tu-darmstadt.de%2fFB04_Logik%2fAFE20%2fAFE7.mp4 HTTP/1.1\r\nHost: sso.tu-darmstadt.de\r\nCookie: <SSO-COOKIE>\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3528.0 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Encoding: gzip, deflate\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 200\r\n'
header: Date: Tue, 13 Apr 2021 21:50:01 GMT
header: Server: Apache
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: 0
header: Strict-Transport-Security: max-age=15768000 ; includeSubDomains
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: DENY
header: X-XSS-Protection: 1; mode=block
header: Content-Type: text/html;charset=UTF-8
header: Content-Language: en
header: Content-Length: 14863
header: Connection: close
WARNING: Falling back on generic information extractor.
[generic] login?service=https://moodleload.hrz.tu-darmstadt.de/FB04_Logik/AFE20/AFE7: Downloading webpage
send: b'GET /login?service=https%3a%2f%2fmoodleload.hrz.tu-darmstadt.de%2fFB04_Logik%2fAFE20%2fAFE7.mp4 HTTP/1.1\r\nHost: sso.tu-darmstadt.de\r\nCookie: TGC=eyJhbGciOiJIUzUxMiJ9.WlhsS05tRllRV2xQYVVwRlVsVlphVXhEU21oaVIyTnBUMmxLYTJGWVNXbE1RMHBzWW0xTmFVOXBTa0pOVkVrMFVUQktSRXhWYUZSTmFsVXlTVzR3TGk0M2FFeDJaRU5PVTBKb2IzcGZlalF4UjNSb1FUbEJMak5RT1RGclpXTXpkRnBpVVVVd2VtbHhhV1F5WVdKU2JEWTBURE42TTFwbWJWSlBNSEUyVVZaU1lWbEtVa0ZsTmpNeFFWSmhaVGhQUVdWalUyOTJVMlp1ZUZob2VuSk5TVmRxWVc1Nk1IVkliaTAzYzBSRU5EVmpWakkxTW1weU1rMU9Va3AxUVRJeGVrUjRNV0U0TkdveVFtWTVWR3hzYnpNeFYwdDJRVVpyUlZZMFZtWkhlakpGV2s1Qk1FRjBjMGRDVVRJeFVrZDBhbUY2UkZwWWVHSTBXakZyV2kxS1ZUUlVTRlJSZGxrNWMwOU1NVVJxVWs1MWFsazVlRzlmWkRsUVNHaHpVM2xKWkhvNE1FOXFYMEk0WVRWM1YwcFVTVEkzWVROc1JFVkxPVEEwTFdveFpsQm1aa0kxWkRseFJVbEdXbUZQZFhGVFMzaGphbDgxUVZCak1qVjRNWGxqWm1GTmVVOVFObEpoVUVwd1dGZEJMbnBXZDBGRWRURnJSR294TFZFNFMxQTBlalV3VVhjPQ.9ynKKUqtVPq_g4kMhGesdEl58Jpjn9AqPyB0QFh2jPybJFi6xS-Z3Gq2KykZItz3RGGlAaKdP7Y5dbGUAUQHuA\r\nAccept-Encoding: *\r\nUser-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3528.0 Safari/537.36\r\nAccept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7\r\nAccept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8\r\nAccept-Language: en-us,en;q=0.5\r\nConnection: close\r\n\r\n'
reply: 'HTTP/1.1 200 200\r\n'
header: Date: Tue, 13 Apr 2021 21:50:01 GMT
header: Server: Apache
header: Cache-Control: no-cache, no-store, max-age=0, must-revalidate
header: Pragma: no-cache
header: Expires: 0
header: Strict-Transport-Security: max-age=15768000 ; includeSubDomains
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: DENY
header: X-XSS-Protection: 1; mode=block
header: Content-Type: text/html;charset=UTF-8
header: Content-Language: en
header: Connection: close
header: Transfer-Encoding: chunked
[generic] <sso url path>: Extracting information
ERROR: Unsupported URL: <sso url>
Traceback (most recent call last):
  File "…/site-packages/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File …/python3.8/site-packages/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "…/python3.8/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "…/python3.8/site-packages/youtube_dl/extractor/generic.py", line 3506, in _real_extract
    raise UnsupportedError(url)
youtube_dl.utils.UnsupportedError: Unsupported URL: <sso url>
</pre>
</details>

But it works when doing this:

```sh
http get <file url> Cookie:<SSO-COOKIE> --session ./session.json --output <OUTPUT-FILE>
```
I think the problem lies somewhere in the redirects the media server does.

What would be the best way to fix this? Is there a way to use a custom download script? Or should I try to fix this by adding some code specific to our media server? Or should I try to add an extractor to youtube-dl? 

I don't really think the last option is possible since I don't now what media server is used an wether any one else is using it.

**Comment by jnnkB** [comment]
Sorry this probably should be a feature request or a question

**Comment by C0D3D3V** [comment]
What exactly do you have in mind?

Do you want moodle-dl to download the videos automatically? Then I need the `responses.log` file, which you can create with `moodle-dl --log-responses`. 

Best would be to send me screenshots where to find it on moodle and how the videoplayer looks like. Is this a completely external player or is the player on moodle?

**Comment by C0D3D3V** [comment]
Can you contact me via mail or Discord: c0d3d3v#8812  Then we can implement your use case.
